# Generated by Django 5.2.4 on 2025-08-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('incharge', models.CharField(max_length=100)),
            ],
        ),
    ]
