# Generated by Django 5.2.4 on 2025-08-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fixed', 'Fixed')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
    ]
