# Generated by Django 5.2.4 on 2025-08-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_area_alter_school_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
